name: Build and Push to ACR (OIDC)
on:
  push:
    branches:
      - '*'
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'Ghiza.sln'
      - 'global.json'
      - '.github/workflows/build-and-push-container.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TAG: ${{ github.ref_name }}-${{ github.sha }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).appId }}
          tenant-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenant }}
          subscription-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}

      - name: Run Azure CLI script
        run: |
          docker build -t ${{ vars.ACR_LOGIN_SERVER }}/ghiza/ghiza:${{ env.TAG }} .
          docker tag ${{ vars.ACR_LOGIN_SERVER }}/ghiza/ghiza:${{ env.TAG }} ${{ vars.ACR_LOGIN_SERVER }}/ghiza/ghiza:latest
          az acr login --name ${{ vars.ACR_NAME }}
          docker push ${{ vars.ACR_LOGIN_SERVER }}/ghiza/ghiza:${{ env.TAG }}