name: Deploy App With Farmer Script (OIDC)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Deploy to Azure Container Apps"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

env:
  BRANCH: ${{ github.ref_name }}
  HASH: ${{ github.sha }}
  TAG: ${{ github.ref_name }}-${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:  
      - name: Log in to Azure
        uses: azure/login@v2.3.0
        with:
          client-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          tenant-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
          subscription-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}

      - name: "Deploy Azure Resources with Farmer script"
        run: dotnet fsi deploy.fsx
                
# jobs:
#   run-fsharp-script:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Install .NET SDK
#         run: |
#           wget https://dot.net/v1/dotnet-install.sh
#           chmod +x dotnet-install.sh
#           ./dotnet-install.sh --install-dir $HOME/dotnet --version latest
#           echo "$HOME/dotnet" >> $GITHUB_PATH

#       - name: Run F# script
#         run: dotnet fsi myscript.fsx
