name: Deploy App With Farmer Script (OIDC)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Deploy to Azure Container Apps"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

env:
  BRANCH: ${{ github.ref_name }}
  HASH: ${{ github.sha }}
  TAG: ${{ github.ref_name }}-${{ github.sha }}
  
jobs:
  deploy-test:
    runs-on: ubuntu-latest
    environment:
      name: TEST
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Verify .NET installation
      run: dotnet --info

    - name: Log in to Azure
      uses: azure/login@v2.3.0
      with:
        client-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
        tenant-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
        subscription-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}

    - name: "Deploy Azure Resources with Farmer script"
      run: dotnet fsi deploy.fsx

  deploy-live:
    runs-on: ubuntu-latest
    environment:
      name: LIVE
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Verify .NET installation
      run: dotnet --info

    - name: Log in to Azure
      uses: azure/login@v2.3.0
      with:
        client-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
        tenant-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
        subscription-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}

    - name: "Deploy Azure Resources with Farmer script"
      run: dotnet fsi deploy.fsx

